- block:


  - name: Ensure haproxy is present
    package:
      name: haproxy
      state: present

  - name: Ensure the haproxy config directory exists
    file:
      path: /etc/haproxy/conf.d
      state: directory

  - name: Ensure the haproxy certs directory exists
    file:
      path: /etc/haproxy/certs
      state: directory

  - name: Ensure the haproxy base config is up to date
    template:
      src: "{{item}}"
      dest: /etc/haproxy/conf.d/{{item}}
      backup: yes
      # Validation for split files does not work, even if they are syntacticly correct
      # validate: '/usr/sbin/haproxy -c -f %s'
    with_items:
      - 30-defaults.cfg
      - 40-https.cfg
      - 30-global.cfg
    notify: Reconfigure haproxy

  - name: Ensure the error files are up to date
    template:
      src: "{{item}}"
      dest: /etc/haproxy/errors/{{item}}
      backup: yes
    with_items:
      - 400.http
      - 403.http
      - 408.http
      - 500.http
      - 502.http
      - 503.http
      - 504.http
    notify: Reload haproxy

  - name: Ensure haproxy gets the new cert and reloads on cert update
    template:
      src: cert_update.sh
      dest: /etc/ssl/update.hooks/haproxy
      mode: 0755
      backup: yes

  - name: Copy the certs for haproxy to the right place and the right format
    command: /etc/ssl/update.hooks/haproxy

  - name: Ensure haproxy is started and enabled
    service:
      name: haproxy
      state: started
      enabled: yes


  become: yes
  tags:
  - haproxy
  - https
  - tls
