- name: Ensure borg is installed with all scripts on valhalla
  hosts: valhalla.fs.tum.de

  pre_tasks:
  - name: Set the ansible_become_user to prevent become
    set_fact:
      ansible_become_user: "{{ansible_user|mandatory}}"

  roles:
  - { role: mediawiki_backup , bin_dir: ~/bin }

  tasks:
  - name: Ensure {{inventory_hostname}} can reach the backup server
    block:

    - name: Ensure the user has a proper ssh key
      user:
        name: "{{ansible_user_id}}"
        generate_ssh_key: true
        ssh_key_type: ed25519
        ssh_key_file: .ssh/bup_ed25519

    - name: Ensure the ssh-key is present in the client config
      blockinfile:
        block: |
          Host {{borg_host}}
            HostName {{groups['backup']|first}}
            User {{hostvars[groups['backup']|first]['borg_user']}}
            IdentityFile ~/.ssh/bup_ed25519
        path: .ssh/config
        create: true

  - name: Ensure the borg repo is present
    shell: PATH=~/bin:$PATH borg-wrapper init -e repokey-blake2
    register: borg_init_result
    failed_when: "borg_init_result.rc != 0 and not (borg_init_result.rc == 2 and 'A repository already exists at' in borg_init_result.stderr)"
    changed_when: "not (borg_init_result.rc == 2 and 'A repository already exists at' in borg_init_result.stderr)"
