- hosts: server
  tasks:

  - name: ensure the koma-admin group is present
    group:
      name: koma-admin
      state: present
    become: yes

  - name: ensure the koma-admins have sudoers permissions
    template:
      src: sudo-koma-admin
      dest: /etc/sudoers.d/koma-admin
      validate: '/usr/sbin/visudo -cf %s'
    become: yes


  - name: ensure the koma-admins are present on the system
    include_role:
      name: user
    vars:
      user_name: "{{ admin_name }}"
      user_shell: "{{ koma_admins[admin_name].shell | default(omit) }}"
      user_ssh_keys: "{{ koma_admins[admin_name].ssh_pubkeys | default(False) }}"
      user_password: "{{ koma_admins[admin_name].password | default(omit) }}"
    loop: "{{ koma_admins.keys() | list }}"
    loop_control:
      loop_var: admin_name

- hosts: server
  roles:

  # Certificate
  - role: letsencrypt
    letsencrypt_staging: no
    letsencrypt_email: homepage@die-koma.org
    letsencrypt_domains:
    - die-koma.org
    - 51.die-koma.org
    - de.komapedia.org
    - honigkuchenpferd.cs.uni-paderborn.de
    - honigkuchenpferd.cs.upb.de
    - komapedia.org
    - twitterwall.die-koma.org
    letsencrypt_use_cert_update_script: yes

  - role: shepherd

  - role: koma-website
    vars:
      koma_website_domains:
      - die-koma.org
      - 51.die-koma.org
      - honigkuchenpferd.cs.uni-paderborn.de
      - honigkuchenpferd.cs.upb.de

  - role: twitterwall

