- block:

  - name: ensure the shepherd service is present
    docker_swarm_service:
      name: shepherd
      image: mazzolino/shepherd:latest
      placement:
        constraints:
        - "node.role==manager"
      mounts:
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        readonly: yes
      env:
      - SLEEP_TIME=30m
      - BLACKLIST_SERVICES="shepherd"

  become: yes
  tags:
  - docker
  - shepherd
