- block:


  - name: ensure the LocalSettings.php is up to date
    template:
      src: LocalSettings.php
      dest: /etc/komapedia/
    notify: "Restart mediawiki"

  - name: ensure the smw.json is present and up to date
    template:
      src: smw.json
      dest: /etc/komapedia/smw.json
    notify: "Restart mediawiki"

  - name: ensure the readonly dir is present
    file:
      dest: /etc/komapedia/readonly
      state: directory

  - name: ensure the files dir is present
    file:
      dest: /srv/komapedia/files
      state: directory

  - name: ensure the cache dir is present
    file:
      dest: /srv/komapedia/cache
      state: directory

  - name: ensure the assets dir is present
    file:
      dest: /srv/komapedia/assets
      state: directory

  - name: deploy Komapedia
    docker_swarm_service:
      name: komapedia
      image: "diekoma/mediawiki:latest"
      restart_config:
        condition: any
      mounts:
      - type: bind
        source: /etc/komapedia/LocalSettings.php
        target: /var/www/html/LocalSettings.php
      - type: bind
        source: /etc/komapedia/smw.json
        target: /var/www/html/extensions/SemanticMediaWiki/.smw.json
      - type: bind
        source: /etc/komapedia/readonly
        target: /var/www/html/ReadOnly
      - type: bind
        source: /srv/komapedia/files
        target: /var/www/html/images
      - type: bind
        source: /srv/komapedia/cache
        target: /var/www/html/cache
      - type: bind
        source: /srv/komapedia/assets
        target: /var/www/html/resources/assets
      publish:
      - published_port: 8181
        target_port: 80

  - name: ensure the haproxy for the komapedia is up to date
    template:
      src: 50-komapedia.org.cfg
      dest: /etc/haproxy/conf.d/
    notify: "Reconfigure haproxy"


  become: yes
  tags:
  - wiki
  - mediawiki
  - komapedia
