- name: Make sure the backup script is up to date
  template:
    src: backup_mediawiki.sh
    dest: "{{bin_dir}}/backup_mediawiki"
    mode: a+x
- name: Ensure the backup is done daily
  cron:
    hour: "{{ 6 | random(start=3,seed=inventory_hostname) }}"
    minute: "{{ 60 | random(seed=inventory_hostname) }}"
    user: "{{ ansible_user }}"
    name: Mediawiki Backup
    job: "PATH={{bin_dir}}:$PATH backup_mediawiki"
